### ISSUE TITLE
Crash when i disconnect from a server

### ISSUE THREAD

**Issue by wanou067** [MrCrayfish/MrCrayfishGunMod#152]
I'm having some problems with cgm, the game crash 50% of the time when I disconnect from a server (not only me, all players)
theses are the logs and crash reported included:

[14:30:52] [Client thread/INFO]: Holder lookups applied
[14:30:57] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@a0da25b:
java.lang.NullPointerException: null
	at com.mrcrayfish.guns.object.Bullet.tick(Bullet.java:55) ~[Bullet.class:?]
	at com.mrcrayfish.guns.client.event.RenderEvents.lambda$onTickBullets$0(RenderEvents.java:1040) ~[RenderEvents.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_282]
	at com.mrcrayfish.guns.client.event.RenderEvents.onTickBullets(RenderEvents.java:1040) ~[RenderEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_251_RenderEvents_onTickBullets_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[14:30:57] [Client thread/ERROR]: Index: 6 Listeners:
[14:30:57] [Client thread/ERROR]: 0: NORMAL
[14:30:57] [Client thread/ERROR]: 1: ASM: class org.blockartistry.DynSurround.client.sound.BackgroundMute clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 2: ASM: class com.mrcrayfish.guns.client.event.SoundEvents deafenPlayer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 3: ASM: class com.mrcrayfish.vehicle.client.EntityRaytracer raytraceEntitiesContinuously(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 4: ASM: net.minecraftforge.common.ForgeInternalHandler@703e6fc0 checkSettings(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 5: ASM: INSTANCE onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 6: ASM: com.mrcrayfish.guns.client.event.RenderEvents@9d11f2f onTickBullets(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 7: ASM: com.mrcrayfish.guns.client.event.RenderEvents@9d11f2f onPreClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 8: ASM: com.mrcrayfish.guns.client.event.RenderEvents@9d11f2f onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 9: ASM: com.mrcrayfish.guns.client.event.GunHandler@373d7782 onPostClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 10: ASM: com.mrcrayfish.guns.client.event.GunHandler@373d7782 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 11: ASM: com.mrcrayfish.guns.client.event.ReloadHandler@404a64e4 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 12: ASM: com.cubgdev.cubga.common.CommonEvents@5fe9627d onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 13: ASM: fr.nathanael2611.modularvoicechat.client.ClientEventHandler@2fd87cdc onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 14: ASM: com.mrcrayfish.vehicle.client.ClientEvents@763ee1a2 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 15: ASM: net.spellcraftgaming.lib.event.ClientTickHandler@39c69751 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 16: ASM: com.creativemd.creativecore.common.event.CreativeTickHandler@452b1005 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 17: ASM: bre.fpsreducer.WakeupEventHandler@426fc498 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 18: ASM: com.mrcrayfish.furniture.client.GifCache@60acc919 onRenderTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 19: ASM: com.cubgdev.cubga.client.particle.ParticleRenderer@361d06fd onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 20: ASM: org.blockartistry.DynSurround.client.handlers.EffectManager@3bf6e615 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 21: ASM: org.blockartistry.DynSurround.client.hud.GuiHUDHandler@14590789 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:30:57] [Client thread/ERROR]: 22: ASM: lumien.randomthings.handler.RTEventHandler@3f2d5c8c tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:30:57] [Client thread/ERROR]: 23: ASM: com.creativemd.creativecore.common.event.CreativeTickHandler@452b1005 onEventTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:30:57] [Client thread/ERROR]: 24: ASM: noppes.npcs.ScriptPlayerEventHandler@72d3c143 forgeEntity(Lnet/minecraftforge/fml/common/eventhandler/Event;)V
[14:30:57] [Client thread/ERROR]: 25: LOWEST
[14:30:57] [Client thread/ERROR]: 26: ASM: noppes.npcs.client.ClientTickHandler@43eef8cb onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:31:09] [Client/INFO]: [com.esotericsoftware.minlog.Log$Logger:print:231]: 55:34  INFO: [kryonet] Connection 6 disconnected.
[14:31:09] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.mrcrayfish.guns.object.Bullet.tick(Bullet.java:55) ~[Bullet.class:?]
	at com.mrcrayfish.guns.client.event.RenderEvents.lambda$onTickBullets$0(RenderEvents.java:1040) ~[RenderEvents.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_282]
	at com.mrcrayfish.guns.client.event.RenderEvents.onTickBullets(RenderEvents.java:1040) ~[RenderEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_251_RenderEvents_onTickBullets_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[14:31:09] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.1.jar)
  ClsPlugin (CustomLoadingScreen-1.12.2-1.4.0.3.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 4/11/21 2:31 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.mrcrayfish.guns.object.Bullet.tick(Bullet.java:55)
	at com.mrcrayfish.guns.client.event.RenderEvents.lambda$onTickBullets$0(RenderEvents.java:1040)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.mrcrayfish.guns.client.event.RenderEvents.onTickBullets(RenderEvents.java:1040)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_251_RenderEvents_onTickBullets_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

The mod was modified a little, but i didn't changed this class, i just added new weapons. Thanks in advance

**Comment by darthvader45** [comment]
I've had this happen on a server with the original unmodified mod file, so something's up with the bullet entity.

**Comment by MrCrayfish** [comment]
I may patch this as a final update to 1.12.2 but after that, the mod will be completely discontinued.

**Comment by darthvader45** [comment]
I hope only the 1.12.2 version is, the ones for 1.17-1.19 are awesome.
