### ISSUE TITLE
Ui issues

### ISSUE THREAD

**Issue by Nlks0n** [MrCrayfish/MrCrayfishGunMod#161]
im having an issue with the ui whenever i press z to open the attachments menu and try to put on any attachments my game crashes
here are some crash logs
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 26.04.21 11:25
Description: mouseClicked event handler

java.util.NoSuchElementException: null
	at java.util.ArrayList$Itr.next(ArrayList.java:854) ~[?:1.8.0_51] {}
	at me.shedaniel.rei.api.client.gui.widgets.Widgets$1.computeNext(Widgets.java:381) ~[?:?] {re:classloading}
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[guava-21.0.jar:?] {}
	at me.shedaniel.rei.api.client.gui.drag.DraggableStackProviderWidget.lambda$from$0(DraggableStackProviderWidget.java:39) ~[?:?] {re:classloading}
	at me.shedaniel.rei.api.client.gui.drag.DraggableStackProviderWidget$$Lambda$11065/1852566917.getHoveredStack(Unknown Source) ~[?:?] {}
	at me.shedaniel.rei.api.client.gui.drag.DraggableStackProviderWidget$1.getHoveredStack(DraggableStackProviderWidget.java:59) ~[?:?] {re:classloading}
	at me.shedaniel.rei.api.client.gui.drag.DraggableStackProvider$1.getHoveredStack(DraggableStackProvider.java:52) ~[?:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.dragging.CurrentDraggingStack.func_231044_a_(CurrentDraggingStack.java:105) ~[?:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ContainerScreenOverlay.func_231044_a_(ContainerScreenOverlay.java:794) ~[?:?] {re:classloading}
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerEvents$16(RoughlyEnoughItemsCore.java:528) ~[?:?] {re:classloading}
	at me.shedaniel.rei.RoughlyEnoughItemsCore$$Lambda$4917/792863094.mouseClicked(Unknown Source) ~[?:?] {}
	at me.shedaniel.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:212) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_398_EventHandlerImplClient_event_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2566/184840411.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onGuiMouseClickedPre(ForgeHooksClient.java:618) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:86) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$9835/1342351974.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$9834/1147489468.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$7969/637216989.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:imm_ptl_mixins.json:client.gui_portal.MixinWindow,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.13.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$506/1184248953.call(Unknown Source) [forge-1.16.5-36.1.13.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
Details:
	Screen name: com.mrcrayfish.guns.client.screen.AttachmentScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$9834/1147489468.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$7969/637216989.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Nlks0n'/277, l='ClientWorld minecraft:overworld', x=-50.61, y=26.00, z=-16.70]]
	Chunk stats: Client Chunks (ImmPtl) 497
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,70,-144), Chunk: (at 0,4,0 in -5,-9; contains blocks -80,0,-144 to -65,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 192747 game time, 192747 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28) [?:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.modify$zzh000$onCrash(Minecraft.java:2548) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.13.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$506/1184248953.call(Unknown Source) [forge-1.16.5-36.1.13.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 756405776 bytes (721 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 3
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.13.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.13
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		notenoughcrashes-3.2.0-forge.jar                  |Not Enough Crashes            |notenoughcrashes              |3.2.0               |DONE      |NOSIGNATURE
		Ma-Enchants-1.16.5-3.6.0.jar                      |Ma Enchants                   |ma-enchants                   |1.16.5-3.6.0        |DONE      |NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |NOSIGNATURE
		TRansliterationLib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |DONE      |NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |NOSIGNATURE
		incontrol-1.16-5.1.6.jar                          |InControl                     |incontrol                     |1.16-5.1.6          |DONE      |NOSIGNATURE
		DoggyTalents-1.16.5-2.0.1.4.jar                   |Doggy Talents 2               |doggytalents                  |task ':jar' property|DONE      |NOSIGNATURE
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |DONE      |NOSIGNATURE
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		totaldarkness-1.3-1.16.5.jar                      |Total Darkness                |totaldarkness                 |1.3-1.16.5          |DONE      |NOSIGNATURE
		villagernames_1.16.5-2.9.jar                      |Villager Names                |villagernames                 |2.9                 |DONE      |NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |DONE      |NOSIGNATURE
		alexsmobs-1.9.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.9.1               |DONE      |NOSIGNATURE
		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |NOSIGNATURE
		configured-0.4.1-1.16.3.jar                       |Configured                    |configured                    |0.4.1-1.16.3        |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |NOSIGNATURE
		catalogue-1.1.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.1.0               |DONE      |NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |DONE      |NOSIGNATURE
		iChunUtil-1.16.5-10.2.0.jar                       |iChunUtil                     |ichunutil                     |10.2.0              |DONE      |NOSIGNATURE
		Enhanced-Vanilla-1.0.4-Forge-1.16.5-36.1.0.jar    |Enhanced Vanilla              |enhanced_vanilla              |1.0.4               |DONE      |NOSIGNATURE
		immersive-portals-0.16-mc1.16.5-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.13-universal.jar                |Forge                         |forge                         |36.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		betterendforge-1.16.4-1.5.1.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		corpse-1.16.5-1.0.1.jar                           |Corpse                        |corpse                        |1.16.5-1.0.1        |DONE      |NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		quiver-2.1-1.16.4.jar                             |Quiver                        |quiver                        |2.1-1.16.4          |DONE      |NOSIGNATURE
		FirstPersonMod-2.0.0.jar                          |FirstPersonModel Mod          |firstpersonmod                |2.0.0               |DONE      |NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |NOSIGNATURE
		RoughlyEnoughItems-6.0.0.217-alpha-forge.jar      |Roughly Enough Items          |roughlyenoughitems            |6.0.0.217-alpha     |DONE      |NOSIGNATURE
		personality-1.16.5-1.0.2.jar                      |Personality                   |personality                   |1.0.2               |DONE      |NOSIGNATURE
		wthit-2.7.0-forge.jar                             |wthit                         |wthit                         |2.7.0               |DONE      |NOSIGNATURE
		notenoughanimations-1.2.3.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.2.3               |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |NOSIGNATURE
		Artifacts-1.16.5-2.8.4.jar                        |Artifacts                     |artifacts                     |1.16.5-2.8.4        |DONE      |NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-311.jar                                |Quark                         |quark                         |r2.4-311            |DONE      |NOSIGNATURE
		backpacked-1.9.1-1.16.3.jar                       |Backpacked                    |backpacked                    |1.9.1               |DONE      |NOSIGNATURE
		backpacker-1.2.3-1.16.3.jar                       |Backpacker                    |backpacker                    |1.2.3               |DONE      |NOSIGNATURE
		twoplayersonehorse-1.16.4-2.0.2.jar               |2 players 1 horse             |twoplayersonehorse            |1.16.4-2.0.2        |DONE      |NOSIGNATURE
		Regrowth-1.16.4-1.16.4-1.35.0.18.jar              |Regrowth Mod                  |regrowth                      |1.16.4-1.35.0.18    |DONE      |NOSIGNATURE
		obfuscate-0.6.0-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		Chunk+Pregenerator-V1.16-3.0.5.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.0.5         |DONE      |NOSIGNATURE
		TheAbyss2+1.9.7+1.16.5.jar                        |TheAbyss                      |theabyss                      |1.9.7               |DONE      |NOSIGNATURE
		architectury-1.12.145-forge.jar                   |Architectury                  |architectury                  |1.12.145            |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		BackTools-1.16.5-10.1.0.jar                       |Back Tools                    |backtools                     |10.1.0              |DONE      |NOSIGNATURE
		OddWaterMobs[1.16.5]_1.2.5.jar                    |Odd Water Mobs                |oddwatermobs                  |1.2.5               |DONE      |NOSIGNATURE
		DamageTilt-1.16-forge-0.1.1.jar                   |DamageTilt                    |damagetilt                    |0.1.1               |DONE      |NOSIGNATURE
		cloth-config-4.11.19-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.19             |DONE      |NOSIGNATURE
		enhancedcelestials-1.0.4-1.16.4.jar               |Enhanced Celestials           |enhancedcelestials            |1.0.4-1.16.4        |DONE      |NOSIGNATURE
		Aquaculture-1.16.5-2.1.18.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.18       |DONE      |NOSIGNATURE
		TA2+beginning+1.0.9+1.16.5.jar                    |[Add-on] The Abyss: The Beginn|thebeginning                  |1.0.9               |DONE      |NOSIGNATURE
		chiselsandbits-0.3.4-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
	Crash Report UUID: c60c9bfe-364b-48eb-9d86-0922a5188c5d
	Suspected Mods: Unknown
	Launched Version: 1.16.5-forge-36.1.13
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 630/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: minecraft:transparent_cosmetics, vanilla, Fabric Mods, cullleaves/smartleaves, file/VanillaTweaks_r966643.zip
	Current Language: English (US)
	CPU: 3x AMD Phenom(tm) II X3 720 Processor
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 10
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GT 630/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 3

**Comment by MrCrayfish** [comment]
Log points to RoughlyEnoughItems mod. Please report to them.
