### ISSUE TITLE
Minecraft 1.12.2 Keeps Crashing When Using The Gun Mod

### ISSUE THREAD

**Issue by Ferer27** [MrCrayfish/MrCrayfishGunMod#240]
Hey, so I got a crash when I'm using MrCrayfish's Gun Mod. I'm actually not sure what causes the problem as I do not understand how to read a crash report. There were no problems using this mod yesterday, it started crashing today. Here's the crash report, thanks!

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Gun Mod (cgm)
Exit Code: -1

---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  FutureMC (future-mc-0.2.8.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.0.2.jar)
Contact their authors BEFORE contacting forge
 
// Hey, that tickles! Hehehe!
 
Time: 1/16/22 8:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail
 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Gun Mod (cgm)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.mrcrayfish.guns.item.GunRegistry.loadProperties(GunRegistry.java:116)
	at com.mrcrayfish.guns.item.GunRegistry.register(GunRegistry.java:50)
	at com.mrcrayfish.guns.item.ItemGun.<init>(ItemGun.java:51)
	at com.mrcrayfish.guns.init.ModGuns.register(ModGuns.java:65)
	at com.mrcrayfish.guns.MrCrayfishGunMod.preInit(MrCrayfishGunMod.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at com.mrcrayfish.guns.object.Gun$Deserializer.deserialize(Gun.java:649)
	at com.mrcrayfish.guns.object.Gun$Deserializer.deserialize(Gun.java:637)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 46 more
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1390898456 bytes (1326 MB) / 2147483648 bytes (2048 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 
	| State | ID                   | Version               | Source                                           | Signature                                |
	|:----- |:-------------------- |:--------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                | minecraft.jar                                    | None                                     |
	| LCH   | mcp                  | 9.42                  | minecraft.jar                                    | None                                     |
	| LCH   | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2855          | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | obfuscate            | 0.4.2                 | minecraft.jar                                    | None                                     |
	| LCH   | securitycraft        | v1.9.0.2              | [1.12.2]+SecurityCraft+v1.9.0.2.jar              | None                                     |
	| LCH   | cdm                  | 0.4.1                 | cdm-0.4.1-mc1.12.2.jar                           | None                                     |
	| LCH   | cfm                  | 6.3.0                 | cfm-6.3.0-mc1.12.2.jar                           | None                                     |
	| LCE   | cgm                  | 0.15.3                | cgm-0.15.3-mc1.12.2.jar                          | None                                     |
	| LC    | customnpcs           | 1.12                  | CustomNPCs_1.12.2-(05Jul20).jar                  | None                                     |
	| LC    | ptrmodellib          | 1.0.5                 | PTRLib-1.0.5.jar                                 | None                                     |
	| LC    | props                | 2.6.3.7               | Decocraft-2.6.3.7_1.12.2.jar                     | None                                     |
	| LC    | flansmod             | 5.10.0                | Flan's+Mod-1.12.2-5.10.0.jar                     | None                                     |
	| LC    | forgelin             | 1.8.4                 | Forgelin-1.8.4.jar                               | None                                     |
	| LC    | futuremc             | 0.2.6                 | future-mc-0.2.8.jar                              | None                                     |
	| LC    | harbour_mania        | 1.0.0                 | Harbour+Mania-1.12.2-1.0.0.jar                   | None                                     |
	| LC    | mts                  | 20.4.0                | Immersive+Vehicles-1.12.2-20.4.0.jar             | None                                     |
	| LC    | helicopterpack       | 2.7.0                 | Helicopter_Pack-2.7.0.jar                        | None                                     |
	| LC    | iav                  | rob-grindes-shrug.png | IAV_Parts_Pack_Beta_3.jar                        | None                                     |
	| LC    | trackapi             | 1.2                   | TrackAPI-1.2.jar                                 | None                                     |
	| LC    | universalmodcore     | 1.1.3                 | UniversalModCore-1.12.2-forge-1.1.3.jar          | None                                     |
	| LC    | immersiverailroading | 1.9.1                 | ImmersiveRailroading-1.12.2-forge-1.9.1.jar      | None                                     |
	| LC    | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                     | None                                     |
	| LC    | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| LC    | unuparts             | 5.0.2                 | UNU+Parts+Pack+[MTS]+1.12.2-20.4.0-5.0.2.jar     | None                                     |
	| LC    | unumilitary          | 4.0.2                 | UNU+Military+Pack+[MTS]+1.12.2-19.15.5-4.0.2.jar | None                                     |
	| LC    | worldedit            | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar         | None                                     |
	| LC    | llibrary             | 1.7.20                | llibrary-1.7.20-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
 
	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.8.4.jar)
 
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
 
ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
FutureMC (future-mc-0.2.8.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.0.2.jar)
 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.23' Renderer: 'NVIDIA GeForce GTX 1060/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 10
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 511.23
	OpenGlRenderer: NVIDIA GeForce GTX 1060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by MrCrayfish** [comment]
Won't fix. Unable to reproduce the issue and unsure how invalid JSON data is being loaded. Update to a modern version of the mod (1.18.2 or above)
