### ISSUE TITLE
MrCrayfishGunMod Open workbanch and crash game pls help me :(

### ISSUE THREAD

**Issue by Demo016** [MrCrayfish/MrCrayfishGunMod#250]
The game crashed whilst exception ticking world
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.mrcrayfish.guns.blockentity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
Exit Code: -1

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/29/22, 4:26 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.mrcrayfish.guns.blockentity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_5995_(SyncedBlockEntity.java:45) ~[cgm-1.1.2-1.18.1.jar%2352!/:1.1.2-1.18.1] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.getUpdatePacket(SyncedBlockEntity.java:51) ~[cgm-1.1.2-1.18.1.jar%2352!/:1.1.2-1.18.1] {re:classloading}
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_183216_(SyncedBlockEntity.java:17) ~[cgm-1.1.2-1.18.1.jar%2352!/:1.1.2-1.18.1] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_5995_(SyncedBlockEntity.java:45) ~[cgm-1.1.2-1.18.1.jar%2352!/:1.1.2-1.18.1] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.getUpdatePacket(SyncedBlockEntity.java:51) ~[cgm-1.1.2-1.18.1.jar%2352!/:1.1.2-1.18.1] {re:classloading}
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_183216_(SyncedBlockEntity.java:17) ~[cgm-1.1.2-1.18.1.jar%2352!/:1.1.2-1.18.1] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Demopro_1688'/113, l='ServerLevel[Yeni Dünya]', x=-10.73, y=151.00, z=22.16]]
	Chunk stats: 2401
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,149,0), Section: (at 0,5,0 in 0,9,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 637 game time, 637 day time
	Level name: Yeni Dünya
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 54060 (now: false), thunder time: 49981 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1385351672 bytes (1321 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2080 Super with Max-Q Design
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1ed3
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34728.05
	Virtual memory used (MB): 17199.76
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 260.91
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Demopro_1688'/113, l='ServerLevel[Yeni Dünya]', x=-10.73, y=151.00, z=22.16]]
	Data Packs: vanilla, mod:framework (incompatible), mod:forge, mod:cgm (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		framework-0.2.2-1.18.1.jar                        |Framework                     |framework                     |0.2.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.63-universal.jar                |Forge                         |forge                         |39.0.63             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		gun-mod-1.1.3-1.18.1.jar                          |MrCrayfish's Gun Mod          |cgm                           |1.1.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 76b66f42-1625-4bb6-995f-f310a936727e
	FML: 39.0
	Forge: net.minecraftforge:39.0.63

**Comment by MrCrayfish** [comment]
Updated to latest version
