### ISSUE TITLE
Problem with aternos 1.18.2 

### ISSUE THREAD

**Issue by TanTanMc** [MrCrayfish/MrCrayfishGunMod#266]
When i open a workbench my game stops 
i use aternos 1.18.2 
i checked the mods are the same each ways 
only this workbench is bad

**Comment by TanTanMc** [comment]
If somewhone is intresed of the logs here:

**Comment by TanTanMc** [comment]
<html>
<body>




[08Mar2022 15:58:29.240] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
359 | net.minecraft.ReportedException: Exception ticking world
360 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
361 | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
362 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
363 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
364 | at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
365 | at java.lang.Thread.run(Thread.java:833) [?:?]
366 | Caused by: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.mrcrayfish.guns.blockentity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
367 | at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_5995_(SyncedBlockEntity.java:45) ~[cgm-1.1.2-1.18.1.jar%2337!/:1.1.2-1.18.1]
368 | at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
369 | at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
370 | at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.getUpdatePacket(SyncedBlockEntity.java:51) ~[cgm-1.1.2-1.18.1.jar%2337!/:1.1.2-1.18.1]
371 | at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_183216_(SyncedBlockEntity.java:17) ~[cgm-1.1.2-1.18.1.jar%2337!/:1.1.2-1.18.1]
372 | at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
373 | at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
374 | at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
375 | at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
376 | at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
377 | at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
378 | at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
379 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
380 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
381 | ... 5 more
382

<br class="Apple-interchange-newline">
</body>
</html>[08Mar2022 15:58:29.240] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.mrcrayfish.guns.blockentity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_5995_(SyncedBlockEntity.java:45) ~[cgm-1.1.2-1.18.1.jar%2337!/:1.1.2-1.18.1]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.getUpdatePacket(SyncedBlockEntity.java:51) ~[cgm-1.1.2-1.18.1.jar%2337!/:1.1.2-1.18.1]
	at com.mrcrayfish.guns.blockentity.SyncedBlockEntity.m_183216_(SyncedBlockEntity.java:17) ~[cgm-1.1.2-1.18.1.jar%2337!/:1.1.2-1.18.1]
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:[370](https://aternos.org/log/#L370)) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2340!/:?]
	... 5 more

**Comment by MrCrayfish** [comment]
1.18.1 version is not compatible with 1.18.2
