### ISSUE TITLE
Crash 1.12.2

### ISSUE THREAD

**Issue by XLEP14** [MrCrayfish/MrCrayfishGunMod#267]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  SecurityCraftLoadingPlugin (1.12.2SecurityCraftv1.9.0.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.16a-mc1.12.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/9/22 6:09 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Gun Mod (cgm)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.mrcrayfish.guns.item.GunRegistry.loadProperties(GunRegistry.java:116)
	at com.mrcrayfish.guns.item.GunRegistry.register(GunRegistry.java:50)
	at com.mrcrayfish.guns.item.ItemGun.<init>(ItemGun.java:51)
	at com.mrcrayfish.guns.init.ModGuns.register(ModGuns.java:65)
	at com.mrcrayfish.guns.MrCrayfishGunMod.preInit(MrCrayfishGunMod.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at com.mrcrayfish.guns.object.Gun$Deserializer.deserialize(Gun.java:649)
	at com.mrcrayfish.guns.object.Gun$Deserializer.deserialize(Gun.java:637)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6161430096 bytes (5875 MB) / 7113539584 bytes (6784 MB) up to 7113539584 bytes (6784 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx6768M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version               | Source                                         | Signature                                |
	|:----- |:-------------------------- |:--------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2                | minecraft.jar                                  | None                                     |
	| LCH   | mcp                        | 9.42                  | minecraft.jar                                  | None                                     |
	| LCH   | FML                        | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                      | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | obfuscate                  | 0.4.2                 | minecraft.jar                                  | None                                     |
	| LCH   | securitycraft              | v1.9.0.2              | 1.12.2SecurityCraftv1.9.0.2.jar                | None                                     |
	| LCH   | damageindicatorsmod        | 1.0                   | [1.12.2]DamageIndicatorsMod-3.5.1.jar          | None                                     |
	| LCH   | bibliocraft                | 2.4.6                 | BiblioCraft-v2.4.6-1.12.2.jar                  | None                                     |
	| LCH   | buildcraftlib              | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | buildcraftcore             | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | buildcraftbuilders         | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | buildcrafttransport        | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | buildcraftsilicon          | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | ic2                        | 2.8.221-ex112         | industrial-craft-2-mod-experimental-1_12_2.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | buildcraftcompat           | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | buildcraftenergy           | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | buildcraftfactory          | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | buildcraftrobotics         | 7.99.24.8             | buildcraft_all_7.99.24.8_1.12.2.jar            | None                                     |
	| LCH   | codechickenlib             | 3.2.3.358             | CodeChickenLib_1.12.2_3.2.3.358_universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | gottschcore                | 1.14.1                | gottschcore-mc1.12.2-f14.23.5.2854-v1.14.1.jar | None                                     |
	| LCH   | fastladder                 | 1.1.1                 | fastladder-mc1.12.2-f14.23.5.2768-v1.1.1.jar   | None                                     |
	| LCE   | cgm                        | 0.15.3                | guns-0.15.3-1.12.2.jar                         | None                                     |
	| LC    | trackapi                   | 1.2                   | trackapi-1.2-1.12.2.jar                        | None                                     |
	| LC    | universalmodcore           | 1.1.3                 | universalmodcore-1.12.2-forge-1.1.3.jar        | None                                     |
	| LC    | immersiverailroading       | 1.9.0                 | ImmersiveRailroading-1.12.2-forge-1.9.0.jar    | None                                     |
	| LC    | ironchest                  | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LC    | jei                        | 4.16.1.302            | jei_1.12.2-4.16.1.302.jar                      | None                                     |
	| LC    | malisiscore                | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LC    | malisisdoors               | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| LC    | supermartijn642configlib   | 1.0.9a                | supermartijn642configlib-1.0.9a-mc1.12.jar     | None                                     |
	| LC    | supermartijn642corelib     | 1.0.16a               | supermartijn642corelib-1.0.16a-mc1.12.jar      | None                                     |
	| LC    | movingelevators            | 1.3.4                 | movingelevators-1.3.4-mc1.12.jar               | None                                     |
	| LC    | nei                        | 2.4.3                 | NotEnoughItems_1.12.2_2.4.3.245_universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | reborncore                 | 3.13.12.447           | RebornCore-1.12.2-3.13.12.447-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | tlauncher_custom_cape_skin | 1.4                   | tlskincape1.12.2-1.4.jar                       | None                                     |
	| LC    | uteamcore                  | 2.2.5.147             | u_team_core-1.12.2-2.2.5.147.jar               | None                                     |
	| LC    | usefulbackpacks            | 1.5.4.85              | useful_backpacks-1.12.2-1.5.4.85.jar           | None                                     |
	| LC    | vehicle                    | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                  | None                                     |
	| LC    | immersiveengineering       | 0.12-98               | ImmersiveEngineering_0.12_98.jar               | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
SecurityCraftLoadingPlugin (1.12.2SecurityCraftv1.9.0.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.16a-mc1.12.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8476' Renderer: 'Intel(R) UHD Graphics'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8476
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by MrCrayfish** [comment]
Please update to a modern version of Minecraft (1.18.2 or above). I no longer push updates for the gun mod on 1.12.2
