### ISSUE TITLE
Recieving a GL Error which crashes the game whenever I shoot a gun

### ISSUE THREAD

**Issue by Sn00kyy** [MrCrayfish/MrCrayfishGunMod#295]
I've tried giving both 8 and 10 gigs to minecraft but whenever I'm using the mods with some others the guns cause the game to crash when shot. Any fixes? It works in singeplayer when I've got it and only a few other mods working, is 10 gigs still not enough for my modpack? Any help is appreciated, crash log is bellow. (This is Minecraft 1.16.5 btw)

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/18/22 3:34 PM
Description: Unexpected error

java.lang.RuntimeException: GL ERROR: [level:HIGH, type:ERROR, source:API, id:0x502, msg:{GL_INVALID_OPERATION error generated. Invalid format for the current read buffer.}]
	at com.seibel.lod.core.render.GLProxy.logMessage(GLProxy.java:138) ~[?:1.6.3a] {re:classloading}
	at com.seibel.lod.core.render.GLProxy$$Lambda$29725/1314514258.accept(Unknown Source) ~[?:?] {}
	at com.seibel.lod.core.util.GLMessageOutputStream.flush(GLMessageOutputStream.java:53) ~[?:1.6.3a] {re:classloading}
	at java.io.PrintStream.write(PrintStream.java:482) ~[?:1.8.0_51] {}
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_51] {}
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[?:1.8.0_51] {}
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104) ~[?:1.8.0_51] {}
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185) ~[?:1.8.0_51] {}
	at java.io.PrintStream.write(PrintStream.java:527) ~[?:1.8.0_51] {}
	at java.io.PrintStream.print(PrintStream.java:669) ~[?:1.8.0_51] {}
	at java.io.PrintStream.append(PrintStream.java:1065) ~[?:1.8.0_51] {}
	at java.io.PrintStream.append(PrintStream.java:57) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2913) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763) ~[?:1.8.0_51] {}
	at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_51] {}
	at java.io.PrintStream.format(PrintStream.java:970) ~[?:1.8.0_51] {}
	at java.io.PrintStream.printf(PrintStream.java:871) ~[?:1.8.0_51] {}
	at org.lwjgl.opengl.GLUtil.printDetail(GLUtil.java:111) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GLUtil.lambda$setupDebugMessageCallback$0(GLUtil.java:51) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GLUtil$$Lambda$29726/553144157.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GL11C.glCopyTexImage2D(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GL11.glCopyTexImage2D(GL11.java:7150) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at com.mrcrayfish.guns.client.render.ScreenTextureState.onRenderWorldLast(ScreenTextureState.java:87) ~[?:1.2.4-1.16.5] {re:classloading}
	at com.mrcrayfish.guns.client.render.ScreenTextureState$$Lambda$30602/2050952326.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3042/1803955991.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3360/1165254118.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:215) ~[?:?] {re:classloading,re:mixin}
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:789) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1027) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:better_diving:GameRenderer renderLevel Transformer,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:better_diving:GameRenderer renderLevel Transformer,pl:mixin:APP:pehkui.mixins.json:reach.client.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat116minus.GameRendererMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:origins.mixins.json:GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.OptifineGameRendererMixin,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:better_diving:GameRenderer renderLevel Transformer,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:better_diving:GameRenderer renderLevel Transformer,pl:mixin:APP:pehkui.mixins.json:reach.client.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat116minus.GameRendererMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:origins.mixins.json:GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.OptifineGameRendererMixin,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:lod.mixins.json:fabric.mixin.networking.accessor.MinecraftClientAccessor,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:lod.mixins.json:fabric.mixin.networking.accessor.MinecraftClientAccessor,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$514/2141984988.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.seibel.lod.core.render.GLProxy.logMessage(GLProxy.java:138) ~[?:1.6.3a] {re:classloading}
	at com.seibel.lod.core.render.GLProxy$$Lambda$29725/1314514258.accept(Unknown Source) ~[?:?] {}
	at com.seibel.lod.core.util.GLMessageOutputStream.flush(GLMessageOutputStream.java:53) ~[?:1.6.3a] {re:classloading}
	at java.io.PrintStream.write(PrintStream.java:482) ~[?:1.8.0_51] {}
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_51] {}
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[?:1.8.0_51] {}
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104) ~[?:1.8.0_51] {}
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185) ~[?:1.8.0_51] {}
	at java.io.PrintStream.write(PrintStream.java:527) ~[?:1.8.0_51] {}
	at java.io.PrintStream.print(PrintStream.java:669) ~[?:1.8.0_51] {}
	at java.io.PrintStream.append(PrintStream.java:1065) ~[?:1.8.0_51] {}
	at java.io.PrintStream.append(PrintStream.java:57) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2913) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763) ~[?:1.8.0_51] {}
	at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_51] {}
	at java.io.PrintStream.format(PrintStream.java:970) ~[?:1.8.0_51] {}
	at java.io.PrintStream.printf(PrintStream.java:871) ~[?:1.8.0_51] {}
	at org.lwjgl.opengl.GLUtil.printDetail(GLUtil.java:111) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GLUtil.lambda$setupDebugMessageCallback$0(GLUtil.java:51) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GLUtil$$Lambda$29726/553144157.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GL11C.glCopyTexImage2D(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GL11.glCopyTexImage2D(GL11.java:7150) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at com.mrcrayfish.guns.client.render.ScreenTextureState.onRenderWorldLast(ScreenTextureState.java:87) ~[?:1.2.4-1.16.5] {re:classloading}
	at com.mrcrayfish.guns.client.render.ScreenTextureState$$Lambda$30602/2050952326.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3042/1803955991.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3360/1165254118.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:215) ~[?:?] {re:classloading,re:mixin}
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:789) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1027) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:better_diving:GameRenderer renderLevel Transformer,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:better_diving:GameRenderer renderLevel Transformer,pl:mixin:APP:pehkui.mixins.json:reach.client.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat116minus.GameRendererMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:origins.mixins.json:GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.OptifineGameRendererMixin,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Uncle_Sn00ky'/538, l='ClientLevel', x=-423.50, y=161.00, z=-576.70]]
	Chunk stats: Client Chunk Cache: 289, 151
	Level dimension: minecraft:overworld
	Level spawn location: World: (-272,72,-512), Chunk: (at 0,4,0 in -17,-32; contains blocks -272,0,-512 to -257,255,-497), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 7562 game time, 7562 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:betterweather.mixins.json:client.MixinClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:lod.mixins.json:fabric.mixin.networking.accessor.MinecraftClientAccessor,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:lod.mixins.json:fabric.mixin.networking.accessor.MinecraftClientAccessor,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$514/2141984988.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

**Comment by MrCrayfish** [comment]
Is this using the latest version?
