### ISSUE TITLE
cgm get UE in crashing launching minecraft

### ISSUE THREAD

**Issue by VGSak47** [MrCrayfish/MrCrayfishGunMod#40]
idk why is crashing :c it does with all the vertions of the mod in 12.2
this is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 12/3/19 10:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Gun Mod (cgm)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.RuntimeException: Error syncing field 'ID_TO_GUN' of class 'com.mrcrayfish.guns.GunConfig'!
	at net.minecraftforge.common.config.ConfigManager.sync(ConfigManager.java:191)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:585)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Error syncing field 'ID_TO_GUN' of class 'com.mrcrayfish.guns.GunConfig'!
	at net.minecraftforge.common.config.ConfigManager.sync(ConfigManager.java:299)
	at net.minecraftforge.common.config.ConfigManager.sync(ConfigManager.java:183)
	... 37 more
Caused by: java.lang.IllegalArgumentException: The map 'ID_TO_GUN' of class 'com.mrcrayfish.guns.GunConfig' has target values which are neither primitive nor an enum!
	at net.minecraftforge.common.config.FieldWrapper$MapWrapper.<init>(FieldWrapper.java:107)
	at net.minecraftforge.common.config.FieldWrapper$MapWrapper.<init>(FieldWrapper.java:67)
	at net.minecraftforge.common.config.FieldWrapper.get(FieldWrapper.java:49)
	at net.minecraftforge.common.config.ConfigManager.sync(ConfigManager.java:245)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_192, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 86534560 bytes (82 MB) / 334491648 bytes (318 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C7 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version       | Source                                             | Signature                                |
	|:----- |:----------------- |:------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft         | 1.12.2        | minecraft.jar                                      | None                                     |
	| UC    | mcp               | 9.42          | minecraft.jar                                      | None                                     |
	| UC    | FML               | 8.0.99.99     | forge-1.12.2-14.23.1.2555.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge             | 14.23.1.2555  | forge-1.12.2-14.23.1.2555.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | obfuscate         | 0.2.6         | minecraft.jar                                      | None                                     |
	| UC    | mercurius_updater | 1.0           | MercuriusUpdater-1.12.2.jar                        | None                                     |
	| UC    | armorchroma       | 1.3           | armorchroma-1.3-1.12.2.jar                         | None                                     |
	| UC    | blockarmor        | 2.4.11        | BlockArmor-1.12.2-2.4.11.jar                       | None                                     |
	| UC    | extendedrenderer  | v1.0          | coroutil-1.12.1-1.2.29.jar                         | None                                     |
	| UC    | coroutil          | 1.12.1-1.2.29 | coroutil-1.12.1-1.2.29.jar                         | None                                     |
	| UC    | configmod         | v1.0          | coroutil-1.12.1-1.2.29.jar                         | None                                     |
	| UC    | desirepaths       | 1.12.1-1.2.8  | desirepaths-1.12.1-1.2.8.jar                       | None                                     |
	| UC    | net.blacklab.lib  | 6.0.2.5       | EBLib-6.0.2.5.jar                                  | None                                     |
	| UC    | enhancedarmaments | 1.3.16        | enhancedarmaments-1.3.16.jar                       | None                                     |
	| UE    | cgm               | 0.12.2        | guns-0.12.2-1.12.2.jar                             | None                                     |
	| UC    | heroicarmory      | 1.1.3         | heroicarmory-1.2.0.jar                             | None                                     |
	| UC    | waila             | 1.8.23        | Hwyla-1.8.23-B38_1.12.jar                          | None                                     |
	| UC    | ironfurnaces      | 1.3.5         | ironfurnaces-1.3.5.jar                             | None                                     |
	| UC    | jei               | 4.8.5.138     | jei_1.12.2-4.8.5.138.jar                           | None                                     |
	| UC    | journeymap        | 1.12.2-5.5.2  | journeymap-1.12.2-5.5.2.jar                        | None                                     |
	| UC    | justenoughbuttons | 1.12-1.2      | justenoughbuttons-1.12.2-1.2.3.jar                 | None                                     |
	| UC    | lmreengaged       | 8.0.1.66      | LittleMaidReengaged-8.0.1.66-unofficial-1.12.2.jar | None                                     |
	| UC    | lootbags          | 2.5.3b        | LootBags-1.12.2-2.5.3b.jar                         | None                                     |
	| UC    | radixcore         | 1.12.x-2.2.1  | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
	| UC    | mca               | 1.12.2-5.3.1  | MCA-1.12.x-5.3.1-universal.jar                     | None                                     |
	| UC    | mclib             | 1.0           | mclib-1.0-1.12.2.jar                               | None                                     |
	| UC    | megaquarry        | 1.4.1         | MegaQuarry-1.4.1-1.12+.jar                         | None                                     |
	| UC    | metamorph         | 1.1.7         | metamorph-1.1.7-1.12.2.jar                         | None                                     |
	| UC    | rwg               | 1.0.1         | Realistic-World-Generation-Mod-1.12.2.jar          | None                                     |
	| UC    | rftl              | 1.0a          | RFTLR1.1.jar                                       | None                                     |
	| UC    | roguelike         | 1.8.0         | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| UC    | simplecorn        | 2.4.1         | SimpleCorn1.12-1.12-2.4.1.jar                      | None                                     |
	| UC    | torcherino        | 7.6           | torcherino-7.6.jar                                 | None                                     |
	| UC    | treechopper       | 1.2.4         | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
	| UC    | uncrafted         | 3.0.1         | Uncrafted 1.12  (v.3.0.1).jar                      | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '3.0.0 - Build 8.15.10.2291' Renderer: 'Intel(R) HD Graphics Family'
	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 9
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0.0 - Build 8.15.10.2291
	OpenGlRenderer: Intel(R) HD Graphics Family
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by EjmShadow** [comment]
same!

**Comment by MrCrayfish** [comment]
Unlikely to fix since 1.12.2 is now considered discontinued.
