### ISSUE TITLE
guns-0.5.0-1.12.2.jar crash

### ISSUE THREAD

**Issue by Kewin05c** [MrCrayfish/MrCrayfishGunMod#5]
I tried to find which mod caused the crash and it was guns mod 0.5.0

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 22/08/18 21:01
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Gun Mod (cgm)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:166)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:159)
	at com.mrcrayfish.guns.network.PacketHandler.init(PacketHandler.java:19)
	at com.mrcrayfish.guns.MrCrayfishGunMod.preInit(MrCrayfishGunMod.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@1144a55a from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5841847768 bytes (5571 MB) / 8039432192 bytes (7667 MB) up to 8039432192 bytes (7667 MB)
	JVM Flags: 2 total; -Xmx8000M -Xms8000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 36 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                  | Signature                                |
	|:----- |:------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2       | minecraft.jar                           | None                                     |
	| UCH   | mcp                 | 9.42         | minecraft.jar                           | None                                     |
	| UCH   | FML                 | 8.0.99.99    | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.4.2705 | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | creativecoredummy   | 1.0.0        | minecraft.jar                           | None                                     |
	| UCH   | obfuscate           | 0.2.5        | minecraft.jar                           | None                                     |
	| UCH   | securitycraft       | v1.8.4.1     | [1.12.x]+SecurityCraft+v1.8.4.1.jar     | None                                     |
	| UCH   | buildcraftlib       | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | buildcraftcore      | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | buildcraftbuilders  | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | buildcraftenergy    | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | buildcraftfactory   | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | buildcraftrobotics  | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | buildcrafttransport | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | buildcraftsilicon   | 7.99.17      | buildcraft-7.99.17.jar                  | None                                     |
	| UCH   | cdm                 | 0.4.1        | cdm-0.4.1-mc1.12.2.jar                  | None                                     |
	| UCH   | cdmcalculator       | 2.4          | CalculatorPlus-2.4+(0.4.0).jar          | None                                     |
	| UCH   | camera              | 1.0.2        | camera-1.0.2.jar                        | None                                     |
	| UCH   | creativecore        | 1.9.9        | CreativeCore_v1.9.22_mc1.12.2.jar       | None                                     |
	| UCH   | modcurrency         | 1.12-1.3.2   | Currency-1.12.0-1.3.2.jar               | None                                     |
	| UCH   | ptrmodellib         | 1.0.0        | Decocraft-2.5.5_1.12.2.jar              | None                                     |
	| UCH   | props               | 2.5.5        | Decocraft-2.5.5_1.12.2.jar              | None                                     |
	| UCH   | deviceai            | 2.4          | Device+AI-2.4.jar                       | None                                     |
	| UCH   | cfm                 | 5.6.1        | furniture-5.6.1-1.12.2.jar              | None                                     |
	| UCH   | gitwebbuilder       | 1.1          | GitWeb+Builder-1.1.jar                  | None                                     |
	| UCEE  | cgm                 | 0.5.0        | guns-0.5.0-1.12.2.jar                   | None                                     |
	| UC    | ic2                 | 2.8.73-ex112 | industrialcraft-2-2.8.73-ex112.jar      | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | lightswitch         | 1.1.2        | lightswitch-1.1.2-mc1.12.2.jar          | None                                     |
	| UC    | malisiscore         | 1.12.2-6.4.0 | malisiscore-1.12.2-6.4.0.jar            | None                                     |
	| UC    | malisisdoors        | 1.12.2-7.3.0 | malisisdoors-1.12.2-7.3.0.jar           | None                                     |
	| UC    | malisisswitches     | 1.12.2-5.1.0 | malisisswitches-1.12.2-5.1.0.jar        | None                                     |
	| UC    | opframe             | 1.4.0        | OnlinePicFrame_v1.4.18_mc1.12.2.jar     | None                                     |
	| UC    | thutcore            | 5.15.1       | ThutCore-1.12.2.jar                     | None                                     |
	| UC    | thutcore_compat     | 1.0          | ThutCore-1.12.2.jar                     | None                                     |
	| UC    | thuttech            | 6.0.15       | thuttech-1.12.2-6.0.15.jar              | None                                     |
	| UD    | mtqfix              | 1.1.0        | minecraft.jar                           | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  jmn.mods.mtqfix.AsmTransformer
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by JacksonPlayz** [comment]
Will be fixed in the next update.

**Comment by sudo-alt-duke** [comment]
did not be fixed it still crashes
