### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by EjmShadow** [MrCrayfish/MrCrayfishGunMod#50]
whenever i start the game i get a weird crash in Gun mod 0.15.0 thats the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 3/25/20 9:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Gun Mod (cgm)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.mrcrayfish.guns.item.GunRegistry.loadProperties(GunRegistry.java:116)
	at com.mrcrayfish.guns.item.GunRegistry.register(GunRegistry.java:50)
	at com.mrcrayfish.guns.item.ItemGun.<init>(ItemGun.java:51)
	at com.mrcrayfish.guns.init.ModGuns.register(ModGuns.java:65)
	at com.mrcrayfish.guns.MrCrayfishGunMod.preInit(MrCrayfishGunMod.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at com.mrcrayfish.guns.object.Gun$Deserializer.deserialize(Gun.java:639)
	at com.mrcrayfish.guns.object.Gun$Deserializer.deserialize(Gun.java:627)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 29197680 bytes (27 MB) / 312766464 bytes (298 MB) up to 2891186176 bytes (2757 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx2769M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 41 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                     | Signature                                |
	|:----- |:----------------- |:----------------- |:------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2            | minecraft.jar                              | None                                     |
	| LCH   | mcp               | 9.42              | minecraft.jar                              | None                                     |
	| LCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy | 1.0.0             | minecraft.jar                              | None                                     |
	| LCH   | obfuscate         | 0.2.6             | minecraft.jar                              | None                                     |
	| LCH   | ambientsounds     | 3.0               | AmbientSounds_v3.0.12_mc1.12.2.jar         | None                                     |
	| LCH   | babymobs          | 1.5.5             | Baby-Mobs-Mod-1.12.2.jar                   | None                                     |
	| LCH   | bacodifficulty    | 1.0.3             | BacoDifficulty-Mod-1.12.2.jar              | None                                     |
	| LCH   | camera            | 1.0.9             | Camera-Mod-1.12.2.jar                      | None                                     |
	| LCH   | carryon           | 1.12.3            | CarryOn+MC1.12.2+v1.12.3.jar               | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCE   | cgm               | 0.15.0            | cgm-0.15.0-mc1.12.2.jar                    | None                                     |
	| LC    | configmod         | v1.0              | Coroutil-1.12.1.jar                        | None                                     |
	| LC    | extendedrenderer  | v1.0              | Coroutil-1.12.1.jar                        | None                                     |
	| LC    | coroutil          | 1.12.1-1.2.15     | Coroutil-1.12.1.jar                        | None                                     |
	| LC    | corpse            | 1.12.2-1.0.6      | Corpse-Mod-1.12.2.jar                      | None                                     |
	| LC    | creativecore      | 1.10.0            | CreativeCore_v1.10.9_mc1.12.2.jar          | None                                     |
	| LC    | doggytalents      | 1.15.1.4          | DoggyTalents-1.12.2-1.15.1.4-universal.jar | None                                     |
	| LC    | emoticons         | 0.2.1             | Emoticons-Mod-1.12.2.jar                   | None                                     |
	| LC    | golems            | 7.1.5             | Extra-Golems-Mod-1.12.2 (1).jar            | None                                     |
	| LC    | fpsreducer        | mc1.12.2-1.14     | FPS-Reducer-Mod-1.12.2.jar                 | None                                     |
	| LC    | ichunutil         | 7.2.1             | iChun-Util-Mod-1.12.2.jar                  | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | ironchest         | 1.12.2-7.0.67.844 | Iron-Chests-Mod-1.12.2.jar                 | None                                     |
	| LC    | jei               | 4.15.0.287        | jei_1.12.2-4.15.0.287.jar                  | None                                     |
	| LC    | journeymap        | 1.12.2-5.5.5b7    | JourneyMap-Mod-1.12.2-Unlimited.jar        | None                                     |
	| LC    | lucky             | 7.6.0             | Lucky-Block-Mod-1.12.2.zip                 | None                                     |
	| LC    | jmcm              | 9.2               | MinecraftCapes Forge 1.12.2.jar            | None                                     |
	| LC    | morph             | 7.1.3             | Morphing-Mod-1.12.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | cfm               | 6.3.1             | MrCrayfishs-Furniture-Mod-1.12.2.jar       | None                                     |
	| LC    | starwars          | 8.9               | StarWars[1.12.2]-8.9.jar                   | None                                     |
	| LC    | subcommonlib      | 1.2.0.1           | SubLib-1.12.2.jar                          | None                                     |
	| LC    | stg               | 1.12.2-1.2.3      | SwingThroughGrass-Mod-1.12.2.jar           | None                                     |
	| LC    | telepads          | $version          | TelePads-Mod-1.12.2.jar                    | None                                     |
	| LC    | lostcities        | 2.0.22            | The-Lost-Cities-Mod-1.12.2.jar             | None                                     |
	| LC    | treechopper       | 1.2.4             | Tree-Chopper-Mod-1.12.2.jar                | None                                     |
	| LC    | car               | 1.2.12            | Ultimate-Car-Mod-1.12.2.jar                | None                                     |
	| LC    | uncrafted         | 3.0.1             | Uncrafted-Mod-1.12.2.jar                   | None                                     |
	| LC    | vanilladeathchest | 1.12.2-1.10.3.4   | Vanilla-Death-Chest-Mod-1.12.2.jar         | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LC    | xlfoodmod         | 1.12.2-1.9.2      | XL-Food-Mod-1.12.2.jar                     | None                                     |
	| LC    | zombie_players    | 1.12.1-1.2.7      | Zombie-Players-Mod-1.12.2.jar              | None                                     |
	| UD    | emoticons_core    | 0.2.1             | minecraft.jar                              | None                                     |

	Loaded coremods (and transformers): 
EmoticonsCore (Emoticons-Mod-1.12.2.jar)
  mchorse.emoticons.core.EmoCoreClassTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.2

**Comment by MrCrayfish** [comment]
Reopen this issue if it's still happens on the latest version coming real soon.
