### ISSUE TITLE
Server crash on mc 1.15.2 and mod 0.16.0

### ISSUE THREAD

**Issue by florpan** [MrCrayfish/MrCrayfishGunMod#66]
Seems to happen when we use grenades. I snooped out this errormessage aswell.
Im a developer but not to familiar with java/minecraft developing so not sure what logs that are relevant. If more info is needed let me know and i'll grab it.

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 7/2/20 3:24 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.world.World.func_195590_a(Lnet/minecraft/particles/IParticleData;ZDDDDDD)V
        at com.mrcrayfish.guns.entity.ThrowableGrenadeEntity.func_70071_h_(ThrowableGrenadeEntity.java:63) ~[?:0.16.0-1.15.2] {re:classloading}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cgm:knockback,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cgm:knockback,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cgm:knockback,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

-- Head --
Thread: Server thread
Stacktrace:
        at com.mrcrayfish.guns.entity.ThrowableGrenadeEntity.func_70071_h_(ThrowableGrenadeEntity.java:63)
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)

-- Entity being ticked --
Details:
        Entity Type: cgm:throwable_grenade (com.mrcrayfish.guns.entity.ThrowableGrenadeEntity)
        Entity ID: 8403
        Entity Name: entity.cgm.throwable_grenade
        Entity's Exact location: -304.97, 78.81, 187.74
        Entity's Block location: World: (-305,78,187), Chunk: (at 15,4,11 in -20,11; contains blocks -320,0,176 to -305,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Entity's Momentum: 0.54, -0.49, 0.55
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
        at net.minecraft.world.World.func_217390_a(World.java:536)
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

        Mod List:
                forge-1.15.2-31.2.0-server.jar Minecraft {minecraft@1.15.2 DONE}
                obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
                betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
                forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
                Aquaculture-1.15.2-2.0.14.jar Aquaculture 2 {aquaculture@1.15.2-2.0.14 DONE}
                cgm-0.16.0-mc1.15.2.jar MrCrayfish's Gun Mod {cgm@0.16.0 DONE}
                BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
                Xaeros_Minimap_20.14.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.14.0 DONE}
                XaerosWorldMap_1.6.4_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.6.4 DONE}
                venture-1.0.0-mc1.15.2.jar Venture {venture@1.0.0 DONE}
                vehicle-0.44.0-mc1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.0 DONE}

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/aa0a6712a405e95b710cb765ace6e30b83a00558
